cookie_name: record_id
cookie_expiration: 120 # cookie lifetime in minutes

tls_cert_file: server.crt
tls_key_file: server.key

# exporter: file
# file_exporter:
#  folder: /tmp/track_entries

exporter: redis
redis_exporter:
  host: localhost
  port: 6379
